#!/usr/bin/env bash

check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                q=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                q=$(echo $a*$q | bc)
                        fi
                        count=$((count + 1))
                done
        else
                q=$3
        fi

        p=$2
        n=$(echo "$1" | tr ':' '=')

        result=$(echo "if($q > $p) 1 else 0" | bc)
	        if ((result == 1)); then
		        ncp=$p
		        p=$q
		        q=$ncp
                fi

        echo "$n$p*$q"
}

if [ $# -ne 1 ]
then
        echo 'Usage: rsa <file>'
        exit 1
else

        while read i
        do

                result=$(factor "$i")
                check_factor $result

        done < "$1"
fi
